# -*- coding: utf-8 -*-
"""TASK 3 Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QouuYkGERO9GfvaBvYqv29Y27riZWMDU
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the Iris dataset
iris_data = pd.read_csv('Iris.csv')  # Ensure 'Iris.csv' is in your working directory

# Set up the figure for multiple plots
fig, axs = plt.subplots(1, 2, figsize=(14, 5))

# Histogram for 'SepalLengthCm' distribution
axs[0].hist(iris_data['SepalLengthCm'], bins=10, color='skyblue', edgecolor='black')
axs[0].set_title('Histogram - Distribution of Sepal Length')
axs[0].set_xlabel('Sepal Length (cm)')
axs[0].set_ylabel('Frequency')

# Bar chart for species distribution
species_counts = iris_data['Species'].value_counts()
axs[1].bar(species_counts.index, species_counts.values, color='salmon', edgecolor='black')
axs[1].set_title('Bar Chart - Species Distribution')
axs[1].set_xlabel('Species')
axs[1].set_ylabel('Count')

# Display the plots
plt.tight_layout()
plt.show()